# coding: utf-8

"""
    ViewPredict AI - YouTube View Count Prediction API

    Complete API for YouTube view count prediction platform with user authentication,  prediction management, analytics, and channel integration. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@viewpredict.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.analytics_insights_get200_response_data_accuracy_trend import AnalyticsInsightsGet200ResponseDataAccuracyTrend
from openapi_server.models.analytics_insights_get200_response_data_patterns_inner import AnalyticsInsightsGet200ResponseDataPatternsInner
from openapi_server.models.analytics_insights_get200_response_data_recommendations_inner import AnalyticsInsightsGet200ResponseDataRecommendationsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AnalyticsInsightsGet200ResponseData(BaseModel):
    """
    AnalyticsInsightsGet200ResponseData
    """ # noqa: E501
    patterns: Optional[List[AnalyticsInsightsGet200ResponseDataPatternsInner]] = None
    recommendations: Optional[List[AnalyticsInsightsGet200ResponseDataRecommendationsInner]] = None
    accuracy_trend: Optional[AnalyticsInsightsGet200ResponseDataAccuracyTrend] = Field(default=None, alias="accuracyTrend")
    __properties: ClassVar[List[str]] = ["patterns", "recommendations", "accuracyTrend"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnalyticsInsightsGet200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in patterns (list)
        _items = []
        if self.patterns:
            for _item in self.patterns:
                if _item:
                    _items.append(_item.to_dict())
            _dict['patterns'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recommendations (list)
        _items = []
        if self.recommendations:
            for _item in self.recommendations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recommendations'] = _items
        # override the default output from pydantic by calling `to_dict()` of accuracy_trend
        if self.accuracy_trend:
            _dict['accuracyTrend'] = self.accuracy_trend.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AnalyticsInsightsGet200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "patterns": [AnalyticsInsightsGet200ResponseDataPatternsInner.from_dict(_item) for _item in obj.get("patterns")] if obj.get("patterns") is not None else None,
            "recommendations": [AnalyticsInsightsGet200ResponseDataRecommendationsInner.from_dict(_item) for _item in obj.get("recommendations")] if obj.get("recommendations") is not None else None,
            "accuracyTrend": AnalyticsInsightsGet200ResponseDataAccuracyTrend.from_dict(obj.get("accuracyTrend")) if obj.get("accuracyTrend") is not None else None
        })
        return _obj


