# coding: utf-8

"""
    ViewPredict AI - YouTube View Count Prediction API

    Complete API for YouTube view count prediction platform with user authentication,  prediction management, analytics, and channel integration. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@viewpredict.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ChannelSettings(BaseModel):
    """
    ChannelSettings
    """ # noqa: E501
    auto_tracking: Optional[StrictBool] = Field(default=None, description="Automatically track predictions for new videos", alias="autoTracking")
    sync_frequency: Optional[StrictStr] = Field(default=None, description="How often to sync channel data", alias="syncFrequency")
    notify_on_new_video: Optional[StrictBool] = Field(default=None, description="Send notification when new video is detected", alias="notifyOnNewVideo")
    auto_create_prediction: Optional[StrictBool] = Field(default=None, description="Automatically create predictions for new videos", alias="autoCreatePrediction")
    __properties: ClassVar[List[str]] = ["autoTracking", "syncFrequency", "notifyOnNewVideo", "autoCreatePrediction"]

    @field_validator('sync_frequency')
    def sync_frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('hourly', 'daily', 'weekly',):
            raise ValueError("must be one of enum values ('hourly', 'daily', 'weekly')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChannelSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ChannelSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "autoTracking": obj.get("autoTracking"),
            "syncFrequency": obj.get("syncFrequency"),
            "notifyOnNewVideo": obj.get("notifyOnNewVideo"),
            "autoCreatePrediction": obj.get("autoCreatePrediction")
        })
        return _obj


