# coding: utf-8

"""
    ViewPredict AI - YouTube View Count Prediction API

    Complete API for YouTube view count prediction platform with user authentication,  prediction management, analytics, and channel integration. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@viewpredict.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.channel_analytics_demographics_age_groups_inner import ChannelAnalyticsDemographicsAgeGroupsInner
from openapi_server.models.channel_analytics_demographics_gender import ChannelAnalyticsDemographicsGender
from openapi_server.models.channel_analytics_demographics_top_countries_inner import ChannelAnalyticsDemographicsTopCountriesInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ChannelAnalyticsDemographics(BaseModel):
    """
    ChannelAnalyticsDemographics
    """ # noqa: E501
    age_groups: Optional[List[ChannelAnalyticsDemographicsAgeGroupsInner]] = Field(default=None, alias="ageGroups")
    gender: Optional[ChannelAnalyticsDemographicsGender] = None
    top_countries: Optional[List[ChannelAnalyticsDemographicsTopCountriesInner]] = Field(default=None, alias="topCountries")
    __properties: ClassVar[List[str]] = ["ageGroups", "gender", "topCountries"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChannelAnalyticsDemographics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in age_groups (list)
        _items = []
        if self.age_groups:
            for _item in self.age_groups:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ageGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of gender
        if self.gender:
            _dict['gender'] = self.gender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in top_countries (list)
        _items = []
        if self.top_countries:
            for _item in self.top_countries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['topCountries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ChannelAnalyticsDemographics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ageGroups": [ChannelAnalyticsDemographicsAgeGroupsInner.from_dict(_item) for _item in obj.get("ageGroups")] if obj.get("ageGroups") is not None else None,
            "gender": ChannelAnalyticsDemographicsGender.from_dict(obj.get("gender")) if obj.get("gender") is not None else None,
            "topCountries": [ChannelAnalyticsDemographicsTopCountriesInner.from_dict(_item) for _item in obj.get("topCountries")] if obj.get("topCountries") is not None else None
        })
        return _obj


