"""remove unique constraint from full_name in users

Revision ID: 7691568718ce
Revises: e5db52325266
Create Date: 2025-10-18 15:58:38.015515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7691568718ce'
down_revision: Union[str, Sequence[str], None] = 'e5db52325266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['full_name'], unique=True)
    # ### end Alembic commands ###
