"""add video_source_type enum and source_type column

Revision ID: d2d9d9bb4916
Revises: e6877fab23ae
Create Date: 2025-10-19 14:53:24.582150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d9d9bb4916'
down_revision: Union[str, Sequence[str], None] = 'e6877fab23ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    video_source_type_enum = sa.Enum('youtube', 'manual', 'test', name='video_source_type')
    video_source_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('videos', sa.Column('source_type', sa.Enum('YOUTUBE', 'MANUAL', 'TEST', name='video_source_type'), nullable=False, server_default='youtube'))
    op.add_column('videos', sa.Column('source_metadata', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('is_synthetic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_synthetic')
    op.drop_column('videos', 'source_metadata')
    op.drop_column('videos', 'source_type')

    op.execute('DROP TYPE IF EXISTS video_source_type')
    # ### end Alembic commands ###
