"""remove unique constraint on channel_id, video_id

Revision ID: db4ae8e69b10
Revises: e88a614d8d0d
Create Date: 2025-10-20 23:21:08.930242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4ae8e69b10'
down_revision: Union[str, Sequence[str], None] = 'e88a614d8d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=False)
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=False)

    # --- Add new composite unique constraints ---
    op.create_unique_constraint(
        'uix_user_channel_unique',
        'channels',
        ['user_id', 'channel_id']
    )

    op.create_unique_constraint(
        'uix_user_video_unique',
        'videos',
        ['user_id', 'video_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Drop composite constraints ---
    op.drop_constraint('uix_user_channel_unique', 'channels', type_='unique')
    op.drop_constraint('uix_user_video_unique', 'videos', type_='unique')

    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=True)
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    # ### end Alembic commands ###
