"""add ChannelType enum and modify Channel schema

Revision ID: e6877fab23ae
Revises: 7691568718ce
Create Date: 2025-10-19 12:00:48.796346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6877fab23ae'
down_revision: Union[str, Sequence[str], None] = '7691568718ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type in PostgreSQL
    channeltype_enum = sa.Enum('REAL', 'DUMMY', name='channeltype')
    channeltype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('channels', sa.Column('type', sa.Enum('REAL', 'DUMMY', name='channeltype'), nullable=False))
    op.add_column('channels', sa.Column('likes', sa.BigInteger(), nullable=True))
    op.alter_column('channels', 'channel_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'channel_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('channels', 'likes')
    op.drop_column('channels', 'type')

    sa.Enum(name='channeltype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
