# coding: utf-8

"""
    ViewPredict AI - YouTube View Count Prediction API

    Complete API for YouTube view count prediction platform with user authentication,  prediction management, analytics, and channel integration. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@viewpredict.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.analytics_api import router as AnalyticsApiRouter
from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.channels_api import router as ChannelsApiRouter
from openapi_server.apis.history_api import router as HistoryApiRouter
from openapi_server.apis.miscellaneous_api import router as MiscellaneousApiRouter
from openapi_server.apis.notifications_api import router as NotificationsApiRouter
from openapi_server.apis.predictions_api import router as PredictionsApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="ViewPredict AI - YouTube View Count Prediction API",
    description="Complete API for YouTube view count prediction platform with user authentication,  prediction management, analytics, and channel integration. ",
    version="1.0.0",
)

app.include_router(AnalyticsApiRouter)
app.include_router(AuthenticationApiRouter)
app.include_router(ChannelsApiRouter)
app.include_router(HistoryApiRouter)
app.include_router(MiscellaneousApiRouter)
app.include_router(NotificationsApiRouter)
app.include_router(PredictionsApiRouter)
app.include_router(UsersApiRouter)
